### ISSUE TITLE
Toolbar buttons stay toggled in HTML mode

### ISSUE THREAD

**Issue by 0nko** [wordpress-mobile/WordPress-Aztec-Android#165]
### Expected

When in HTML mode all style toolbar buttons should be disabled and non-toggled.

### Observed

When the cursor is on styled text and buttons are toggled in visual mode, the buttons stay toggled in HTML mode, as well.

![image](https://cloud.githubusercontent.com/assets/1522856/21692396/f4d8780e-d37c-11e6-83f4-4a2b0c3337c5.png)

#### Tested
This is only observed  when integrated in the WP app.

**Comment by theck13** [comment]
This actually isn't an issue with Aztec.  Since Aztec and WordPress use the same file names for the format toolbar button selectors (e.g. ```format_bar_button_bold_selector```), the app (i.e. WordPress) is overriding the library (i.e. Aztec).  The app and library ```format_bar_button_bold_selector``` files are shown below as an example.

**APP**
```
<selector
    xmlns:android="http://schemas.android.com/apk/res/android" >

    <item android:state_checked="true" android:drawable="@drawable/format_bar_button_bold_highlighted"/>
    <item android:state_pressed="true" android:drawable="@drawable/format_bar_button_bold_highlighted"/>
    <item android:state_enabled="false" android:drawable="@drawable/format_bar_button_bold_disabled"/>
    <item android:drawable="@drawable/format_bar_button_bold"/>

</selector>
```

**LIB**
```
<selector
    xmlns:android="http://schemas.android.com/apk/res/android" >

    <item android:state_enabled="false" android:drawable="@drawable/format_bar_button_bold_disabled"/>
    <item android:state_checked="true" android:drawable="@drawable/format_bar_button_bold_highlighted"/>
    <item android:state_pressed="true" android:drawable="@drawable/format_bar_button_bold_highlighted"/>
    <item android:drawable="@drawable/format_bar_button_bold"/>

</selector>
```

In the app, the ```android:state_checked``` state is being shown even though the button is disabled since it is above the ```android:state_enabled``` state.  Changing the selector resources in the app to mimic the library fixes the issue.  I submitted a [pull request](https://github.com/wordpress-mobile/WordPress-Android/pull/5023) against the `feature/aztec-integration` branch to do just that.
