### ISSUE TITLE
In some cases selected heading is allways "Paragraph" for partialy selected multiline text

### ISSUE THREAD

**Issue by khaykov** [wordpress-mobile/WordPress-Aztec-Android#78]
Noticed a really minor issue - while multiline text with heading style applied to it is selected, the selected heading will always be "Paragraph" unless we have at lest one line fully selected.

To illustrate:

This works fine. "Heading 1" is marked as selected. Notice that "World" if fully selected.
![good_2](https://cloud.githubusercontent.com/assets/728822/18335306/6cfba9c2-75b9-11e6-8c8f-e7ce46b6438b.png)

This also works fine. "Heading 1" is marked as selected. "something" is fully selected.
![good_1](https://cloud.githubusercontent.com/assets/728822/18335325/8c62abda-75b9-11e6-96ac-557404607ea1.png)

This doesn't work as expected. "Paragraph" is marked as selected. No line is fully selected.
![bad_1](https://cloud.githubusercontent.com/assets/728822/18335364/cccb0bcc-75b9-11e6-8f2d-c98c12bed79d.png)

**Comment by theck13** [comment]
This same behavior occurs for all block formats (i.e. List, Quote, and Heading).  See the screenshots below for details.  Notice the style is highlighted in the toolbar in the left and center instances, but not the right.

![ordered](https://cloud.githubusercontent.com/assets/3827611/21167808/4f547a30-c16c-11e6-80b7-6b087728e621.png)

![unordered](https://cloud.githubusercontent.com/assets/3827611/21167813/51bedb80-c16c-11e6-8b62-90525195f7bd.png)

![quote](https://cloud.githubusercontent.com/assets/3827611/21167648/1d12a890-c16b-11e6-8075-271fcda341fc.png)

The root cause is the associated [containsList](https://github.com/wordpress-mobile/WordPress-Aztec-Android/blob/develop/aztec/src/main/kotlin/org/wordpress/aztec/formatting/BlockFormatter.kt#L343-L347), [containQuote](https://github.com/wordpress-mobile/WordPress-Aztec-Android/blob/develop/aztec/src/main/kotlin/org/wordpress/aztec/formatting/BlockFormatter.kt#L397-L401), and [containsHeading](https://github.com/wordpress-mobile/WordPress-Aztec-Android/blob/develop/aztec/src/main/kotlin/org/wordpress/aztec/formatting/LineBlockFormatter.kt#L171-L175) methods which consider a selection to contain a block format if the selection is on only one line or the entire line is selected.

Another scenario is when multiple formats are within a selection.  Do we want to highlight all formats within a selection?  See the screenshot below for an example.  In this case, ordered list, unordered list, and quote would be highlighted in the toolbar.

![multiple](https://cloud.githubusercontent.com/assets/3827611/21167682/67411dde-c16b-11e6-9ddc-fd7d02401915.png)
